id: P006895
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21769
  title: གབ་ཚིག་གསར་བསྒྲིགས
  author: ''
  volumes:
    ed25cc390fd746648ae586ecbd0c4de5:
      image_group_id: I4870
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
