id: IA2F68683
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:36:23+00:00'
last_modified: '2022-06-08T09:24:28.453720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21769
  title: གབ་ཚིག་གསར་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9A5A:
      image_group_id: I4870
      title: ''
      total_pages: 206
      order: 1
      base_file: 9A5A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
